sources:
  - name: Authors
    handler:
      graphql:
        endpoint: ./src/mock-schema/mock-schema.graphql

transforms:
  - mock:
      if: true
      initializeStore: ./src/resolvers/authors.query.ts#initializeStore
      mocks:
        - apply: Query.author
          custom: ./src/resolvers/authors.query.ts#author
        - apply: Mutation.uploadFile
          custom: ./src/resolvers/authors.mutation.ts#uploadFile
        - apply: Mutation.uploadFileWithUnion
          custom: ./src/resolvers/authors.mutation.ts#uploadFileWithUnion

require:
  - ts-node/register/transpile-only

serve:
  port: 4000
  cors: { origin: http://localhost:3000 }
  playground: true
  browser: false
